# .github/workflows/docker.yml

name: Build (but don’t push)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install React dependencies
        working-directory: ./login-abuse-ui
        run: npm ci

      - name: Build React app
        working-directory: ./login-abuse-ui
        run: npm run build

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests/test_tracker.py

      # ─────────────────────────────────────────────────────────────
      # Instead of logging in & pushing, just build the image
      # ─────────────────────────────────────────────────────────────
      - name: Build Docker image only
        run: |
          docker build -t login-abuse-tracker:test .
